// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_process_image (
hls::stream<struct ap_axiu<16, 1, 1, 1 > > (&video_in),
hls::stream<struct ap_axiu<16, 1, 1, 1 > > (&video_out),
int height,
int width);
