// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Mat2AXIvideo (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        height,
        width,
        img_data_stream_0_V_dout,
        img_data_stream_0_V_empty_n,
        img_data_stream_0_V_read,
        img_data_stream_1_V_dout,
        img_data_stream_1_V_empty_n,
        img_data_stream_1_V_read,
        video_out_TDATA,
        video_out_TVALID,
        video_out_TREADY,
        video_out_TKEEP,
        video_out_TSTRB,
        video_out_TUSER,
        video_out_TLAST,
        video_out_TID,
        video_out_TDEST
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state6 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] height;
input  [31:0] width;
input  [7:0] img_data_stream_0_V_dout;
input   img_data_stream_0_V_empty_n;
output   img_data_stream_0_V_read;
input  [7:0] img_data_stream_1_V_dout;
input   img_data_stream_1_V_empty_n;
output   img_data_stream_1_V_read;
output  [15:0] video_out_TDATA;
output   video_out_TVALID;
input   video_out_TREADY;
output  [1:0] video_out_TKEEP;
output  [1:0] video_out_TSTRB;
output  [0:0] video_out_TUSER;
output  [0:0] video_out_TLAST;
output  [0:0] video_out_TID;
output  [0:0] video_out_TDEST;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg img_data_stream_0_V_read;
reg img_data_stream_1_V_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [15:0] video_out_V_data_V_1_data_out;
reg    video_out_V_data_V_1_vld_in;
wire    video_out_V_data_V_1_vld_out;
wire    video_out_V_data_V_1_ack_in;
wire    video_out_V_data_V_1_ack_out;
reg   [15:0] video_out_V_data_V_1_payload_A;
reg   [15:0] video_out_V_data_V_1_payload_B;
reg    video_out_V_data_V_1_sel_rd;
reg    video_out_V_data_V_1_sel_wr;
wire    video_out_V_data_V_1_sel;
wire    video_out_V_data_V_1_load_A;
wire    video_out_V_data_V_1_load_B;
reg   [1:0] video_out_V_data_V_1_state;
wire    video_out_V_data_V_1_state_cmp_full;
wire   [1:0] video_out_V_keep_V_1_data_out;
reg    video_out_V_keep_V_1_vld_in;
wire    video_out_V_keep_V_1_vld_out;
wire    video_out_V_keep_V_1_ack_in;
wire    video_out_V_keep_V_1_ack_out;
reg    video_out_V_keep_V_1_sel_rd;
wire    video_out_V_keep_V_1_sel;
reg   [1:0] video_out_V_keep_V_1_state;
wire   [1:0] video_out_V_strb_V_1_data_out;
reg    video_out_V_strb_V_1_vld_in;
wire    video_out_V_strb_V_1_vld_out;
wire    video_out_V_strb_V_1_ack_in;
wire    video_out_V_strb_V_1_ack_out;
reg    video_out_V_strb_V_1_sel_rd;
wire    video_out_V_strb_V_1_sel;
reg   [1:0] video_out_V_strb_V_1_state;
reg   [0:0] video_out_V_user_V_1_data_out;
reg    video_out_V_user_V_1_vld_in;
wire    video_out_V_user_V_1_vld_out;
wire    video_out_V_user_V_1_ack_in;
wire    video_out_V_user_V_1_ack_out;
reg   [0:0] video_out_V_user_V_1_payload_A;
reg   [0:0] video_out_V_user_V_1_payload_B;
reg    video_out_V_user_V_1_sel_rd;
reg    video_out_V_user_V_1_sel_wr;
wire    video_out_V_user_V_1_sel;
wire    video_out_V_user_V_1_load_A;
wire    video_out_V_user_V_1_load_B;
reg   [1:0] video_out_V_user_V_1_state;
wire    video_out_V_user_V_1_state_cmp_full;
reg   [0:0] video_out_V_last_V_1_data_out;
reg    video_out_V_last_V_1_vld_in;
wire    video_out_V_last_V_1_vld_out;
wire    video_out_V_last_V_1_ack_in;
wire    video_out_V_last_V_1_ack_out;
reg   [0:0] video_out_V_last_V_1_payload_A;
reg   [0:0] video_out_V_last_V_1_payload_B;
reg    video_out_V_last_V_1_sel_rd;
reg    video_out_V_last_V_1_sel_wr;
wire    video_out_V_last_V_1_sel;
wire    video_out_V_last_V_1_load_A;
wire    video_out_V_last_V_1_load_B;
reg   [1:0] video_out_V_last_V_1_state;
wire    video_out_V_last_V_1_state_cmp_full;
wire   [0:0] video_out_V_id_V_1_data_out;
reg    video_out_V_id_V_1_vld_in;
wire    video_out_V_id_V_1_vld_out;
wire    video_out_V_id_V_1_ack_in;
wire    video_out_V_id_V_1_ack_out;
reg    video_out_V_id_V_1_sel_rd;
wire    video_out_V_id_V_1_sel;
reg   [1:0] video_out_V_id_V_1_state;
wire   [0:0] video_out_V_dest_V_1_data_out;
reg    video_out_V_dest_V_1_vld_in;
wire    video_out_V_dest_V_1_vld_out;
wire    video_out_V_dest_V_1_ack_in;
wire    video_out_V_dest_V_1_ack_out;
reg    video_out_V_dest_V_1_sel_rd;
wire    video_out_V_dest_V_1_sel;
reg   [1:0] video_out_V_dest_V_1_state;
reg    img_data_stream_0_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond_i_reg_314;
reg    img_data_stream_1_V_blk_n;
reg    video_out_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] exitcond_i_reg_314_pp0_iter1_reg;
reg   [10:0] t_V_1_reg_208;
wire   [10:0] rows_V_fu_219_p1;
reg    ap_block_state1;
wire   [10:0] cols_V_fu_223_p1;
wire   [10:0] r_V_fu_227_p2;
wire   [0:0] exitcond1_i_fu_238_p2;
wire    ap_CS_fsm_state2;
reg    ap_block_state2;
wire   [10:0] i_V_fu_243_p2;
reg   [10:0] i_V_reg_309;
wire   [0:0] exitcond_i_fu_249_p2;
wire    ap_block_state3_pp0_stage0_iter0;
reg    ap_block_state4_pp0_stage0_iter1;
reg    ap_block_state4_io;
wire    ap_block_state5_pp0_stage0_iter2;
reg    ap_block_state5_io;
reg    ap_block_pp0_stage0_11001;
wire   [10:0] j_V_fu_254_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] axi_last_V_fu_260_p2;
reg   [0:0] axi_last_V_reg_323;
wire   [15:0] tmp_data_V_fu_269_p3;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg   [10:0] t_V_reg_197;
wire    ap_CS_fsm_state6;
reg   [0:0] tmp_user_V_fu_140;
reg    ap_block_pp0_stage0_01001;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 video_out_V_data_V_1_sel_rd = 1'b0;
#0 video_out_V_data_V_1_sel_wr = 1'b0;
#0 video_out_V_data_V_1_state = 2'd0;
#0 video_out_V_keep_V_1_sel_rd = 1'b0;
#0 video_out_V_keep_V_1_state = 2'd0;
#0 video_out_V_strb_V_1_sel_rd = 1'b0;
#0 video_out_V_strb_V_1_state = 2'd0;
#0 video_out_V_user_V_1_sel_rd = 1'b0;
#0 video_out_V_user_V_1_sel_wr = 1'b0;
#0 video_out_V_user_V_1_state = 2'd0;
#0 video_out_V_last_V_1_sel_rd = 1'b0;
#0 video_out_V_last_V_1_sel_wr = 1'b0;
#0 video_out_V_last_V_1_state = 2'd0;
#0 video_out_V_id_V_1_sel_rd = 1'b0;
#0 video_out_V_id_V_1_state = 2'd0;
#0 video_out_V_dest_V_1_sel_rd = 1'b0;
#0 video_out_V_dest_V_1_state = 2'd0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((video_out_V_data_V_1_ack_in == 1'b0) | (video_out_V_dest_V_1_ack_in == 1'b0) | (video_out_V_id_V_1_ack_in == 1'b0) | (video_out_V_last_V_1_ack_in == 1'b0) | (video_out_V_user_V_1_ack_in == 1'b0) | (video_out_V_strb_V_1_ack_in == 1'b0) | (video_out_V_keep_V_1_ack_in == 1'b0)) & (exitcond1_i_fu_238_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((video_out_V_data_V_1_ack_in == 1'b0) | (video_out_V_dest_V_1_ack_in == 1'b0) | (video_out_V_id_V_1_ack_in == 1'b0) | (video_out_V_last_V_1_ack_in == 1'b0) | (video_out_V_user_V_1_ack_in == 1'b0) | (video_out_V_strb_V_1_ack_in == 1'b0) | (video_out_V_keep_V_1_ack_in == 1'b0)) & (exitcond1_i_fu_238_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state3)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((~((video_out_V_data_V_1_ack_in == 1'b0) | (video_out_V_dest_V_1_ack_in == 1'b0) | (video_out_V_id_V_1_ack_in == 1'b0) | (video_out_V_last_V_1_ack_in == 1'b0) | (video_out_V_user_V_1_ack_in == 1'b0) | (video_out_V_strb_V_1_ack_in == 1'b0) | (video_out_V_keep_V_1_ack_in == 1'b0)) & (exitcond1_i_fu_238_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_data_V_1_sel_rd <= 1'b0;
    end else begin
        if (((video_out_V_data_V_1_ack_out == 1'b1) & (video_out_V_data_V_1_vld_out == 1'b1))) begin
            video_out_V_data_V_1_sel_rd <= ~video_out_V_data_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_data_V_1_sel_wr <= 1'b0;
    end else begin
        if (((video_out_V_data_V_1_ack_in == 1'b1) & (video_out_V_data_V_1_vld_in == 1'b1))) begin
            video_out_V_data_V_1_sel_wr <= ~video_out_V_data_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_data_V_1_state <= 2'd0;
    end else begin
        if ((((video_out_V_data_V_1_state == 2'd2) & (video_out_V_data_V_1_vld_in == 1'b0)) | ((video_out_V_data_V_1_state == 2'd3) & (video_out_V_data_V_1_vld_in == 1'b0) & (video_out_V_data_V_1_ack_out == 1'b1)))) begin
            video_out_V_data_V_1_state <= 2'd2;
        end else if ((((video_out_V_data_V_1_state == 2'd1) & (video_out_V_data_V_1_ack_out == 1'b0)) | ((video_out_V_data_V_1_state == 2'd3) & (video_out_V_data_V_1_ack_out == 1'b0) & (video_out_V_data_V_1_vld_in == 1'b1)))) begin
            video_out_V_data_V_1_state <= 2'd1;
        end else if (((~((video_out_V_data_V_1_vld_in == 1'b0) & (video_out_V_data_V_1_ack_out == 1'b1)) & ~((video_out_V_data_V_1_ack_out == 1'b0) & (video_out_V_data_V_1_vld_in == 1'b1)) & (video_out_V_data_V_1_state == 2'd3)) | ((video_out_V_data_V_1_state == 2'd1) & (video_out_V_data_V_1_ack_out == 1'b1)) | ((video_out_V_data_V_1_state == 2'd2) & (video_out_V_data_V_1_vld_in == 1'b1)))) begin
            video_out_V_data_V_1_state <= 2'd3;
        end else begin
            video_out_V_data_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_dest_V_1_sel_rd <= 1'b0;
    end else begin
        if (((video_out_V_dest_V_1_ack_out == 1'b1) & (video_out_V_dest_V_1_vld_out == 1'b1))) begin
            video_out_V_dest_V_1_sel_rd <= ~video_out_V_dest_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_dest_V_1_state <= 2'd0;
    end else begin
        if ((((video_out_V_dest_V_1_state == 2'd2) & (video_out_V_dest_V_1_vld_in == 1'b0)) | ((video_out_V_dest_V_1_state == 2'd3) & (video_out_V_dest_V_1_vld_in == 1'b0) & (video_out_V_dest_V_1_ack_out == 1'b1)))) begin
            video_out_V_dest_V_1_state <= 2'd2;
        end else if ((((video_out_V_dest_V_1_state == 2'd1) & (video_out_V_dest_V_1_ack_out == 1'b0)) | ((video_out_V_dest_V_1_state == 2'd3) & (video_out_V_dest_V_1_ack_out == 1'b0) & (video_out_V_dest_V_1_vld_in == 1'b1)))) begin
            video_out_V_dest_V_1_state <= 2'd1;
        end else if (((~((video_out_V_dest_V_1_vld_in == 1'b0) & (video_out_V_dest_V_1_ack_out == 1'b1)) & ~((video_out_V_dest_V_1_ack_out == 1'b0) & (video_out_V_dest_V_1_vld_in == 1'b1)) & (video_out_V_dest_V_1_state == 2'd3)) | ((video_out_V_dest_V_1_state == 2'd1) & (video_out_V_dest_V_1_ack_out == 1'b1)) | ((video_out_V_dest_V_1_state == 2'd2) & (video_out_V_dest_V_1_vld_in == 1'b1)))) begin
            video_out_V_dest_V_1_state <= 2'd3;
        end else begin
            video_out_V_dest_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_id_V_1_sel_rd <= 1'b0;
    end else begin
        if (((video_out_V_id_V_1_ack_out == 1'b1) & (video_out_V_id_V_1_vld_out == 1'b1))) begin
            video_out_V_id_V_1_sel_rd <= ~video_out_V_id_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_id_V_1_state <= 2'd0;
    end else begin
        if ((((video_out_V_id_V_1_state == 2'd2) & (video_out_V_id_V_1_vld_in == 1'b0)) | ((video_out_V_id_V_1_state == 2'd3) & (video_out_V_id_V_1_vld_in == 1'b0) & (video_out_V_id_V_1_ack_out == 1'b1)))) begin
            video_out_V_id_V_1_state <= 2'd2;
        end else if ((((video_out_V_id_V_1_state == 2'd1) & (video_out_V_id_V_1_ack_out == 1'b0)) | ((video_out_V_id_V_1_state == 2'd3) & (video_out_V_id_V_1_ack_out == 1'b0) & (video_out_V_id_V_1_vld_in == 1'b1)))) begin
            video_out_V_id_V_1_state <= 2'd1;
        end else if (((~((video_out_V_id_V_1_vld_in == 1'b0) & (video_out_V_id_V_1_ack_out == 1'b1)) & ~((video_out_V_id_V_1_ack_out == 1'b0) & (video_out_V_id_V_1_vld_in == 1'b1)) & (video_out_V_id_V_1_state == 2'd3)) | ((video_out_V_id_V_1_state == 2'd1) & (video_out_V_id_V_1_ack_out == 1'b1)) | ((video_out_V_id_V_1_state == 2'd2) & (video_out_V_id_V_1_vld_in == 1'b1)))) begin
            video_out_V_id_V_1_state <= 2'd3;
        end else begin
            video_out_V_id_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_keep_V_1_sel_rd <= 1'b0;
    end else begin
        if (((video_out_V_keep_V_1_ack_out == 1'b1) & (video_out_V_keep_V_1_vld_out == 1'b1))) begin
            video_out_V_keep_V_1_sel_rd <= ~video_out_V_keep_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_keep_V_1_state <= 2'd0;
    end else begin
        if ((((video_out_V_keep_V_1_state == 2'd2) & (video_out_V_keep_V_1_vld_in == 1'b0)) | ((video_out_V_keep_V_1_state == 2'd3) & (video_out_V_keep_V_1_vld_in == 1'b0) & (video_out_V_keep_V_1_ack_out == 1'b1)))) begin
            video_out_V_keep_V_1_state <= 2'd2;
        end else if ((((video_out_V_keep_V_1_state == 2'd1) & (video_out_V_keep_V_1_ack_out == 1'b0)) | ((video_out_V_keep_V_1_state == 2'd3) & (video_out_V_keep_V_1_ack_out == 1'b0) & (video_out_V_keep_V_1_vld_in == 1'b1)))) begin
            video_out_V_keep_V_1_state <= 2'd1;
        end else if (((~((video_out_V_keep_V_1_vld_in == 1'b0) & (video_out_V_keep_V_1_ack_out == 1'b1)) & ~((video_out_V_keep_V_1_ack_out == 1'b0) & (video_out_V_keep_V_1_vld_in == 1'b1)) & (video_out_V_keep_V_1_state == 2'd3)) | ((video_out_V_keep_V_1_state == 2'd1) & (video_out_V_keep_V_1_ack_out == 1'b1)) | ((video_out_V_keep_V_1_state == 2'd2) & (video_out_V_keep_V_1_vld_in == 1'b1)))) begin
            video_out_V_keep_V_1_state <= 2'd3;
        end else begin
            video_out_V_keep_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_last_V_1_sel_rd <= 1'b0;
    end else begin
        if (((video_out_V_last_V_1_ack_out == 1'b1) & (video_out_V_last_V_1_vld_out == 1'b1))) begin
            video_out_V_last_V_1_sel_rd <= ~video_out_V_last_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_last_V_1_sel_wr <= 1'b0;
    end else begin
        if (((video_out_V_last_V_1_ack_in == 1'b1) & (video_out_V_last_V_1_vld_in == 1'b1))) begin
            video_out_V_last_V_1_sel_wr <= ~video_out_V_last_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_last_V_1_state <= 2'd0;
    end else begin
        if ((((video_out_V_last_V_1_state == 2'd2) & (video_out_V_last_V_1_vld_in == 1'b0)) | ((video_out_V_last_V_1_state == 2'd3) & (video_out_V_last_V_1_vld_in == 1'b0) & (video_out_V_last_V_1_ack_out == 1'b1)))) begin
            video_out_V_last_V_1_state <= 2'd2;
        end else if ((((video_out_V_last_V_1_state == 2'd1) & (video_out_V_last_V_1_ack_out == 1'b0)) | ((video_out_V_last_V_1_state == 2'd3) & (video_out_V_last_V_1_ack_out == 1'b0) & (video_out_V_last_V_1_vld_in == 1'b1)))) begin
            video_out_V_last_V_1_state <= 2'd1;
        end else if (((~((video_out_V_last_V_1_vld_in == 1'b0) & (video_out_V_last_V_1_ack_out == 1'b1)) & ~((video_out_V_last_V_1_ack_out == 1'b0) & (video_out_V_last_V_1_vld_in == 1'b1)) & (video_out_V_last_V_1_state == 2'd3)) | ((video_out_V_last_V_1_state == 2'd1) & (video_out_V_last_V_1_ack_out == 1'b1)) | ((video_out_V_last_V_1_state == 2'd2) & (video_out_V_last_V_1_vld_in == 1'b1)))) begin
            video_out_V_last_V_1_state <= 2'd3;
        end else begin
            video_out_V_last_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_strb_V_1_sel_rd <= 1'b0;
    end else begin
        if (((video_out_V_strb_V_1_ack_out == 1'b1) & (video_out_V_strb_V_1_vld_out == 1'b1))) begin
            video_out_V_strb_V_1_sel_rd <= ~video_out_V_strb_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_strb_V_1_state <= 2'd0;
    end else begin
        if ((((video_out_V_strb_V_1_state == 2'd2) & (video_out_V_strb_V_1_vld_in == 1'b0)) | ((video_out_V_strb_V_1_state == 2'd3) & (video_out_V_strb_V_1_vld_in == 1'b0) & (video_out_V_strb_V_1_ack_out == 1'b1)))) begin
            video_out_V_strb_V_1_state <= 2'd2;
        end else if ((((video_out_V_strb_V_1_state == 2'd1) & (video_out_V_strb_V_1_ack_out == 1'b0)) | ((video_out_V_strb_V_1_state == 2'd3) & (video_out_V_strb_V_1_ack_out == 1'b0) & (video_out_V_strb_V_1_vld_in == 1'b1)))) begin
            video_out_V_strb_V_1_state <= 2'd1;
        end else if (((~((video_out_V_strb_V_1_vld_in == 1'b0) & (video_out_V_strb_V_1_ack_out == 1'b1)) & ~((video_out_V_strb_V_1_ack_out == 1'b0) & (video_out_V_strb_V_1_vld_in == 1'b1)) & (video_out_V_strb_V_1_state == 2'd3)) | ((video_out_V_strb_V_1_state == 2'd1) & (video_out_V_strb_V_1_ack_out == 1'b1)) | ((video_out_V_strb_V_1_state == 2'd2) & (video_out_V_strb_V_1_vld_in == 1'b1)))) begin
            video_out_V_strb_V_1_state <= 2'd3;
        end else begin
            video_out_V_strb_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_user_V_1_sel_rd <= 1'b0;
    end else begin
        if (((video_out_V_user_V_1_ack_out == 1'b1) & (video_out_V_user_V_1_vld_out == 1'b1))) begin
            video_out_V_user_V_1_sel_rd <= ~video_out_V_user_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_user_V_1_sel_wr <= 1'b0;
    end else begin
        if (((video_out_V_user_V_1_ack_in == 1'b1) & (video_out_V_user_V_1_vld_in == 1'b1))) begin
            video_out_V_user_V_1_sel_wr <= ~video_out_V_user_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_user_V_1_state <= 2'd0;
    end else begin
        if ((((video_out_V_user_V_1_state == 2'd2) & (video_out_V_user_V_1_vld_in == 1'b0)) | ((video_out_V_user_V_1_state == 2'd3) & (video_out_V_user_V_1_vld_in == 1'b0) & (video_out_V_user_V_1_ack_out == 1'b1)))) begin
            video_out_V_user_V_1_state <= 2'd2;
        end else if ((((video_out_V_user_V_1_state == 2'd1) & (video_out_V_user_V_1_ack_out == 1'b0)) | ((video_out_V_user_V_1_state == 2'd3) & (video_out_V_user_V_1_ack_out == 1'b0) & (video_out_V_user_V_1_vld_in == 1'b1)))) begin
            video_out_V_user_V_1_state <= 2'd1;
        end else if (((~((video_out_V_user_V_1_vld_in == 1'b0) & (video_out_V_user_V_1_ack_out == 1'b1)) & ~((video_out_V_user_V_1_ack_out == 1'b0) & (video_out_V_user_V_1_vld_in == 1'b1)) & (video_out_V_user_V_1_state == 2'd3)) | ((video_out_V_user_V_1_state == 2'd1) & (video_out_V_user_V_1_ack_out == 1'b1)) | ((video_out_V_user_V_1_state == 2'd2) & (video_out_V_user_V_1_vld_in == 1'b1)))) begin
            video_out_V_user_V_1_state <= 2'd3;
        end else begin
            video_out_V_user_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_fu_249_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        t_V_1_reg_208 <= j_V_fu_254_p2;
    end else if ((~((video_out_V_data_V_1_ack_in == 1'b0) | (video_out_V_dest_V_1_ack_in == 1'b0) | (video_out_V_id_V_1_ack_in == 1'b0) | (video_out_V_last_V_1_ack_in == 1'b0) | (video_out_V_user_V_1_ack_in == 1'b0) | (video_out_V_strb_V_1_ack_in == 1'b0) | (video_out_V_keep_V_1_ack_in == 1'b0)) & (exitcond1_i_fu_238_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        t_V_1_reg_208 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        t_V_reg_197 <= 11'd0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        t_V_reg_197 <= i_V_reg_309;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_reg_314 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_user_V_fu_140 <= 1'd0;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_user_V_fu_140 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_fu_249_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        axi_last_V_reg_323 <= axi_last_V_fu_260_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exitcond_i_reg_314 <= exitcond_i_fu_249_p2;
        exitcond_i_reg_314_pp0_iter1_reg <= exitcond_i_reg_314;
    end
end

always @ (posedge ap_clk) begin
    if ((~((video_out_V_data_V_1_ack_in == 1'b0) | (video_out_V_dest_V_1_ack_in == 1'b0) | (video_out_V_id_V_1_ack_in == 1'b0) | (video_out_V_last_V_1_ack_in == 1'b0) | (video_out_V_user_V_1_ack_in == 1'b0) | (video_out_V_strb_V_1_ack_in == 1'b0) | (video_out_V_keep_V_1_ack_in == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
        i_V_reg_309 <= i_V_fu_243_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((video_out_V_data_V_1_load_A == 1'b1)) begin
        video_out_V_data_V_1_payload_A <= tmp_data_V_fu_269_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((video_out_V_data_V_1_load_B == 1'b1)) begin
        video_out_V_data_V_1_payload_B <= tmp_data_V_fu_269_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((video_out_V_last_V_1_load_A == 1'b1)) begin
        video_out_V_last_V_1_payload_A <= axi_last_V_reg_323;
    end
end

always @ (posedge ap_clk) begin
    if ((video_out_V_last_V_1_load_B == 1'b1)) begin
        video_out_V_last_V_1_payload_B <= axi_last_V_reg_323;
    end
end

always @ (posedge ap_clk) begin
    if ((video_out_V_user_V_1_load_A == 1'b1)) begin
        video_out_V_user_V_1_payload_A <= tmp_user_V_fu_140;
    end
end

always @ (posedge ap_clk) begin
    if ((video_out_V_user_V_1_load_B == 1'b1)) begin
        video_out_V_user_V_1_payload_B <= tmp_user_V_fu_140;
    end
end

always @ (*) begin
    if ((exitcond_i_fu_249_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if ((~((video_out_V_data_V_1_ack_in == 1'b0) | (video_out_V_dest_V_1_ack_in == 1'b0) | (video_out_V_id_V_1_ack_in == 1'b0) | (video_out_V_last_V_1_ack_in == 1'b0) | (video_out_V_user_V_1_ack_in == 1'b0) | (video_out_V_strb_V_1_ack_in == 1'b0) | (video_out_V_keep_V_1_ack_in == 1'b0)) & (exitcond1_i_fu_238_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((video_out_V_data_V_1_ack_in == 1'b0) | (video_out_V_dest_V_1_ack_in == 1'b0) | (video_out_V_id_V_1_ack_in == 1'b0) | (video_out_V_last_V_1_ack_in == 1'b0) | (video_out_V_user_V_1_ack_in == 1'b0) | (video_out_V_strb_V_1_ack_in == 1'b0) | (video_out_V_keep_V_1_ack_in == 1'b0)) & (exitcond1_i_fu_238_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_314 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_data_stream_0_V_blk_n = img_data_stream_0_V_empty_n;
    end else begin
        img_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_314 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_data_stream_0_V_read = 1'b1;
    end else begin
        img_data_stream_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_314 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_data_stream_1_V_blk_n = img_data_stream_1_V_empty_n;
    end else begin
        img_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_314 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_data_stream_1_V_read = 1'b1;
    end else begin
        img_data_stream_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((exitcond_i_reg_314_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((exitcond_i_reg_314 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        video_out_TDATA_blk_n = video_out_V_data_V_1_state[1'd1];
    end else begin
        video_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((video_out_V_data_V_1_sel == 1'b1)) begin
        video_out_V_data_V_1_data_out = video_out_V_data_V_1_payload_B;
    end else begin
        video_out_V_data_V_1_data_out = video_out_V_data_V_1_payload_A;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_314 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        video_out_V_data_V_1_vld_in = 1'b1;
    end else begin
        video_out_V_data_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_314 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        video_out_V_dest_V_1_vld_in = 1'b1;
    end else begin
        video_out_V_dest_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_314 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        video_out_V_id_V_1_vld_in = 1'b1;
    end else begin
        video_out_V_id_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_314 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        video_out_V_keep_V_1_vld_in = 1'b1;
    end else begin
        video_out_V_keep_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((video_out_V_last_V_1_sel == 1'b1)) begin
        video_out_V_last_V_1_data_out = video_out_V_last_V_1_payload_B;
    end else begin
        video_out_V_last_V_1_data_out = video_out_V_last_V_1_payload_A;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_314 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        video_out_V_last_V_1_vld_in = 1'b1;
    end else begin
        video_out_V_last_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_314 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        video_out_V_strb_V_1_vld_in = 1'b1;
    end else begin
        video_out_V_strb_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((video_out_V_user_V_1_sel == 1'b1)) begin
        video_out_V_user_V_1_data_out = video_out_V_user_V_1_payload_B;
    end else begin
        video_out_V_user_V_1_data_out = video_out_V_user_V_1_payload_A;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_314 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        video_out_V_user_V_1_vld_in = 1'b1;
    end else begin
        video_out_V_user_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((video_out_V_data_V_1_ack_in == 1'b0) | (video_out_V_dest_V_1_ack_in == 1'b0) | (video_out_V_id_V_1_ack_in == 1'b0) | (video_out_V_last_V_1_ack_in == 1'b0) | (video_out_V_user_V_1_ack_in == 1'b0) | (video_out_V_strb_V_1_ack_in == 1'b0) | (video_out_V_keep_V_1_ack_in == 1'b0)) & (exitcond1_i_fu_238_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if ((~((video_out_V_data_V_1_ack_in == 1'b0) | (video_out_V_dest_V_1_ack_in == 1'b0) | (video_out_V_id_V_1_ack_in == 1'b0) | (video_out_V_last_V_1_ack_in == 1'b0) | (video_out_V_user_V_1_ack_in == 1'b0) | (video_out_V_strb_V_1_ack_in == 1'b0) | (video_out_V_keep_V_1_ack_in == 1'b0)) & (exitcond1_i_fu_238_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((exitcond_i_fu_249_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((exitcond_i_fu_249_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((exitcond_i_reg_314 == 1'd0) & (img_data_stream_1_V_empty_n == 1'b0)) | ((exitcond_i_reg_314 == 1'd0) & (img_data_stream_0_V_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((1'b1 == ap_block_state5_io) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state4_io) | ((exitcond_i_reg_314 == 1'd0) & (img_data_stream_1_V_empty_n == 1'b0)) | ((exitcond_i_reg_314 == 1'd0) & (img_data_stream_0_V_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((1'b1 == ap_block_state5_io) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state4_io) | ((exitcond_i_reg_314 == 1'd0) & (img_data_stream_1_V_empty_n == 1'b0)) | ((exitcond_i_reg_314 == 1'd0) & (img_data_stream_0_V_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2 = ((video_out_V_data_V_1_ack_in == 1'b0) | (video_out_V_dest_V_1_ack_in == 1'b0) | (video_out_V_id_V_1_ack_in == 1'b0) | (video_out_V_last_V_1_ack_in == 1'b0) | (video_out_V_user_V_1_ack_in == 1'b0) | (video_out_V_strb_V_1_ack_in == 1'b0) | (video_out_V_keep_V_1_ack_in == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_io = ((exitcond_i_reg_314 == 1'd0) & (video_out_V_data_V_1_ack_in == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1 = (((exitcond_i_reg_314 == 1'd0) & (img_data_stream_1_V_empty_n == 1'b0)) | ((exitcond_i_reg_314 == 1'd0) & (img_data_stream_0_V_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state5_io = ((exitcond_i_reg_314_pp0_iter1_reg == 1'd0) & (video_out_V_data_V_1_ack_in == 1'b0));
end

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign axi_last_V_fu_260_p2 = ((t_V_1_reg_208 == r_V_fu_227_p2) ? 1'b1 : 1'b0);

assign cols_V_fu_223_p1 = width[10:0];

assign exitcond1_i_fu_238_p2 = ((t_V_reg_197 == rows_V_fu_219_p1) ? 1'b1 : 1'b0);

assign exitcond_i_fu_249_p2 = ((t_V_1_reg_208 == cols_V_fu_223_p1) ? 1'b1 : 1'b0);

assign i_V_fu_243_p2 = (t_V_reg_197 + 11'd1);

assign j_V_fu_254_p2 = (t_V_1_reg_208 + 11'd1);

assign r_V_fu_227_p2 = ($signed(11'd2047) + $signed(cols_V_fu_223_p1));

assign rows_V_fu_219_p1 = height[10:0];

assign tmp_data_V_fu_269_p3 = {{img_data_stream_1_V_dout}, {img_data_stream_0_V_dout}};

assign video_out_TDATA = video_out_V_data_V_1_data_out;

assign video_out_TDEST = video_out_V_dest_V_1_data_out;

assign video_out_TID = video_out_V_id_V_1_data_out;

assign video_out_TKEEP = video_out_V_keep_V_1_data_out;

assign video_out_TLAST = video_out_V_last_V_1_data_out;

assign video_out_TSTRB = video_out_V_strb_V_1_data_out;

assign video_out_TUSER = video_out_V_user_V_1_data_out;

assign video_out_TVALID = video_out_V_dest_V_1_state[1'd0];

assign video_out_V_data_V_1_ack_in = video_out_V_data_V_1_state[1'd1];

assign video_out_V_data_V_1_ack_out = video_out_TREADY;

assign video_out_V_data_V_1_load_A = (video_out_V_data_V_1_state_cmp_full & ~video_out_V_data_V_1_sel_wr);

assign video_out_V_data_V_1_load_B = (video_out_V_data_V_1_state_cmp_full & video_out_V_data_V_1_sel_wr);

assign video_out_V_data_V_1_sel = video_out_V_data_V_1_sel_rd;

assign video_out_V_data_V_1_state_cmp_full = ((video_out_V_data_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign video_out_V_data_V_1_vld_out = video_out_V_data_V_1_state[1'd0];

assign video_out_V_dest_V_1_ack_in = video_out_V_dest_V_1_state[1'd1];

assign video_out_V_dest_V_1_ack_out = video_out_TREADY;

assign video_out_V_dest_V_1_data_out = 1'd0;

assign video_out_V_dest_V_1_sel = video_out_V_dest_V_1_sel_rd;

assign video_out_V_dest_V_1_vld_out = video_out_V_dest_V_1_state[1'd0];

assign video_out_V_id_V_1_ack_in = video_out_V_id_V_1_state[1'd1];

assign video_out_V_id_V_1_ack_out = video_out_TREADY;

assign video_out_V_id_V_1_data_out = 1'd0;

assign video_out_V_id_V_1_sel = video_out_V_id_V_1_sel_rd;

assign video_out_V_id_V_1_vld_out = video_out_V_id_V_1_state[1'd0];

assign video_out_V_keep_V_1_ack_in = video_out_V_keep_V_1_state[1'd1];

assign video_out_V_keep_V_1_ack_out = video_out_TREADY;

assign video_out_V_keep_V_1_data_out = 2'd3;

assign video_out_V_keep_V_1_sel = video_out_V_keep_V_1_sel_rd;

assign video_out_V_keep_V_1_vld_out = video_out_V_keep_V_1_state[1'd0];

assign video_out_V_last_V_1_ack_in = video_out_V_last_V_1_state[1'd1];

assign video_out_V_last_V_1_ack_out = video_out_TREADY;

assign video_out_V_last_V_1_load_A = (video_out_V_last_V_1_state_cmp_full & ~video_out_V_last_V_1_sel_wr);

assign video_out_V_last_V_1_load_B = (video_out_V_last_V_1_state_cmp_full & video_out_V_last_V_1_sel_wr);

assign video_out_V_last_V_1_sel = video_out_V_last_V_1_sel_rd;

assign video_out_V_last_V_1_state_cmp_full = ((video_out_V_last_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign video_out_V_last_V_1_vld_out = video_out_V_last_V_1_state[1'd0];

assign video_out_V_strb_V_1_ack_in = video_out_V_strb_V_1_state[1'd1];

assign video_out_V_strb_V_1_ack_out = video_out_TREADY;

assign video_out_V_strb_V_1_data_out = 2'd0;

assign video_out_V_strb_V_1_sel = video_out_V_strb_V_1_sel_rd;

assign video_out_V_strb_V_1_vld_out = video_out_V_strb_V_1_state[1'd0];

assign video_out_V_user_V_1_ack_in = video_out_V_user_V_1_state[1'd1];

assign video_out_V_user_V_1_ack_out = video_out_TREADY;

assign video_out_V_user_V_1_load_A = (video_out_V_user_V_1_state_cmp_full & ~video_out_V_user_V_1_sel_wr);

assign video_out_V_user_V_1_load_B = (video_out_V_user_V_1_state_cmp_full & video_out_V_user_V_1_sel_wr);

assign video_out_V_user_V_1_sel = video_out_V_user_V_1_sel_rd;

assign video_out_V_user_V_1_state_cmp_full = ((video_out_V_user_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign video_out_V_user_V_1_vld_out = video_out_V_user_V_1_state[1'd0];

endmodule //Mat2AXIvideo
