// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xprocess_image.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XProcess_image_CfgInitialize(XProcess_image *InstancePtr, XProcess_image_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_bus_BaseAddress = ConfigPtr->Control_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XProcess_image_Start(XProcess_image *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XProcess_image_ReadReg(InstancePtr->Control_bus_BaseAddress, XPROCESS_IMAGE_CONTROL_BUS_ADDR_AP_CTRL) & 0x80;
    XProcess_image_WriteReg(InstancePtr->Control_bus_BaseAddress, XPROCESS_IMAGE_CONTROL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XProcess_image_IsDone(XProcess_image *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XProcess_image_ReadReg(InstancePtr->Control_bus_BaseAddress, XPROCESS_IMAGE_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XProcess_image_IsIdle(XProcess_image *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XProcess_image_ReadReg(InstancePtr->Control_bus_BaseAddress, XPROCESS_IMAGE_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XProcess_image_IsReady(XProcess_image *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XProcess_image_ReadReg(InstancePtr->Control_bus_BaseAddress, XPROCESS_IMAGE_CONTROL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XProcess_image_EnableAutoRestart(XProcess_image *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XProcess_image_WriteReg(InstancePtr->Control_bus_BaseAddress, XPROCESS_IMAGE_CONTROL_BUS_ADDR_AP_CTRL, 0x80);
}

void XProcess_image_DisableAutoRestart(XProcess_image *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XProcess_image_WriteReg(InstancePtr->Control_bus_BaseAddress, XPROCESS_IMAGE_CONTROL_BUS_ADDR_AP_CTRL, 0);
}

void XProcess_image_Set_height(XProcess_image *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XProcess_image_WriteReg(InstancePtr->Control_bus_BaseAddress, XPROCESS_IMAGE_CONTROL_BUS_ADDR_HEIGHT_DATA, Data);
}

u32 XProcess_image_Get_height(XProcess_image *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XProcess_image_ReadReg(InstancePtr->Control_bus_BaseAddress, XPROCESS_IMAGE_CONTROL_BUS_ADDR_HEIGHT_DATA);
    return Data;
}

void XProcess_image_Set_width(XProcess_image *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XProcess_image_WriteReg(InstancePtr->Control_bus_BaseAddress, XPROCESS_IMAGE_CONTROL_BUS_ADDR_WIDTH_DATA, Data);
}

u32 XProcess_image_Get_width(XProcess_image *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XProcess_image_ReadReg(InstancePtr->Control_bus_BaseAddress, XPROCESS_IMAGE_CONTROL_BUS_ADDR_WIDTH_DATA);
    return Data;
}

void XProcess_image_InterruptGlobalEnable(XProcess_image *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XProcess_image_WriteReg(InstancePtr->Control_bus_BaseAddress, XPROCESS_IMAGE_CONTROL_BUS_ADDR_GIE, 1);
}

void XProcess_image_InterruptGlobalDisable(XProcess_image *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XProcess_image_WriteReg(InstancePtr->Control_bus_BaseAddress, XPROCESS_IMAGE_CONTROL_BUS_ADDR_GIE, 0);
}

void XProcess_image_InterruptEnable(XProcess_image *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XProcess_image_ReadReg(InstancePtr->Control_bus_BaseAddress, XPROCESS_IMAGE_CONTROL_BUS_ADDR_IER);
    XProcess_image_WriteReg(InstancePtr->Control_bus_BaseAddress, XPROCESS_IMAGE_CONTROL_BUS_ADDR_IER, Register | Mask);
}

void XProcess_image_InterruptDisable(XProcess_image *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XProcess_image_ReadReg(InstancePtr->Control_bus_BaseAddress, XPROCESS_IMAGE_CONTROL_BUS_ADDR_IER);
    XProcess_image_WriteReg(InstancePtr->Control_bus_BaseAddress, XPROCESS_IMAGE_CONTROL_BUS_ADDR_IER, Register & (~Mask));
}

void XProcess_image_InterruptClear(XProcess_image *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XProcess_image_WriteReg(InstancePtr->Control_bus_BaseAddress, XPROCESS_IMAGE_CONTROL_BUS_ADDR_ISR, Mask);
}

u32 XProcess_image_InterruptGetEnabled(XProcess_image *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XProcess_image_ReadReg(InstancePtr->Control_bus_BaseAddress, XPROCESS_IMAGE_CONTROL_BUS_ADDR_IER);
}

u32 XProcess_image_InterruptGetStatus(XProcess_image *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XProcess_image_ReadReg(InstancePtr->Control_bus_BaseAddress, XPROCESS_IMAGE_CONTROL_BUS_ADDR_ISR);
}

