# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2018.2
# Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================


/opt/Xilinx/Vivado/2018.2/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xczu9eg-ffvb1156-2-i-es2 ../xilinx_com_hls_process_image_1_0.zip
